# 0: start
# 1: slider
# 2: plug probe
# 3: probe circuit
# 4: wrap cable
# 5: stop
task_order: [0, 1]
debug: true
pre_height_above_button: 0.08
linear_vel_z: 0.01 # positive going up, negative going down; NOTE: changing this affects force_z_diff_threshold. Low velocities are more stable
force_z_diff_threshold: 3.0 # if diff between current force and mean force is greater, stop
probe_holder_pose: [0.5991508364677429, -0.01071108877658844, 0.12583768367767334, 90.0, 0.0, 90.0]
probe_holder_pick_perceive_pose: [TODO]
probe_pre_pick_from_holder_pose: [TODO]
perceive_board_pose: [0.4634, 0.1357, 0.432, -180.0, 0.0, 153.0]
