pre_height_above_button: 0.1
linear_vel_z: 0.01 # positive going up, negative going down; NOTE: changing this affects force_z_diff_threshold. Low velocities are more stable
force_z_diff_threshold: 3.0 # if diff between current force and mean force is greater, stop
